name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      working-directory: ./source/server
      run:  |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Build
      working-directory: ./source/server
      run:  | 
        go build --ldflags="-w -s" -o "saynice-server-amd64-linux-v1"

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:

    - name: Deploy to Server
      working-directory: ./source/server
      uses: AEnterprise/rsync-deploy@v1.0
      env:
        DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        ARGS: -avz
        SERVER_PORT: 22
        FOLDER: saynice-server-amd64-linux-v1
        SERVER_IP: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        SERVER_DESTINATION: /home/app/saynice

    # - name: Test
    #   run:  |
    #     cd source/server
    #     go test -v .
